### PR TITLE
(maint) Temporarily add back in tasks

### PR DESCRIPTION
**Pull request by sarameisburger**
Things were breaking without them so we are adding them back in for now

### CODE REVIEW

**Comment by MikaelSmith** [comment]
Should we target this at an older branch and merge-up?

**Comment by mwaggett** [comment]
yes

**Comment by sarameisburger** [comment]
@MikaelSmith i'll retarget to 1.5

**Comment by sarameisburger** [comment]
opened new pull request https://github.com/puppetlabs/cpp-pcp-client/pull/245 closing this one

**Pull request closed without merging**
