### PR TITLE
(maint) Log broker WS URI on open event

### PR DESCRIPTION
**Pull request by parisiale**

### CODE REVIEW

**Comment by parisiale** [comment]
This needs https://github.com/puppetlabs/pxp-agent/pull/244.

**Comment by MikaelSmith** [comment]
Merging this means we'll have to branch cpp-pcp-client if we need any more fixes for pxp-agent stable.

**Comment by kylog** [comment]
@MikaelSmith why would we have an additional branch for cpp-pcp-client? I didn't follow that.

Related, should both these logging changes go to stable?

**Comment by parisiale** [comment]
@kylog would be nice to have them, but @joshcooper asked to avoid merging into stable today.

**Comment by kylog** [comment]
Ah okay, got it. Thanks.

**Comment by MikaelSmith** [comment]
I meant, if we need to make fixes to cpp-pcp-client needed by pxp-agent#stable before we merge pxp-agent#master up to stable, we'll have to branch this to add the fixes and do another cpp-pcp-client bug fix release. That's a problem we can deal with when it arises, so just thinking it through.

**Pull request merged**
