### PR TITLE
(maint) Improvements to CI, take 2

### PR DESCRIPTION
**Pull request by MikaelSmith**

### CODE REVIEW

**Comment by MikaelSmith** [comment]
jenkins please test this on aix71-POWER,amazon6-64,arista4-32,ciscoxr-64,cumulus25-64,debian7-32a,osx1011-64,redhat6-s390x,sles11-s390x,solaris10-SPARC,solaris11-64,ubuntu1604-POWER,windows2012r2-64

**Comment by MikaelSmith** [comment]
jenkins please test this on aix71-POWER,amazon6-64,arista4-32,ciscoxr-64,cisconx-64,cumulus25-64,debian7-32a,osx1011-64,redhat6-S390X,sles11-S390X,solaris10-SPARC,solaris11-64,ubuntu1604-POWER,windows2012r2-64

**Comment by MikaelSmith** [comment]
jenkins please test this on aix71-POWER,amazon6-64,arista4-32,ciscoxr-64,cisconx-64,cumulus25-64,debian7-32a,osx1011-64,redhat6-S390X,sles11-S390X,solaris10-SPARC,solaris11-64,ubuntu1604-POWER,windows2012r2-64

**Comment by MikaelSmith** [comment]
jenkins please test this on aix71-POWER,amazon6-64,arista4-32,ciscoxr-64,cisconx-64,cumulus25-64,debian7-32a,osx1011-64,redhat6-S390X,sles11-S390X,solaris10-SPARC,solaris11-64,ubuntu1604-POWER,windows2012r2-64

**Comment by MikaelSmith** [comment]
jenkins please test this on aix71-POWER,amazon6-64,arista4-32,ciscoxr-64,cisconx-64,cumulus25-64,debian8-32a,osx1011-64,redhat6-S390X,sles11-S390X,solaris10-SPARC,solaris11-64,ubuntu1604-POWER,windows2012r2-64

**Comment by MikaelSmith** [comment]
jenkins please test this on aix71-POWER,amazon6-64,arista4-32,ciscoxr-64,cisconx-64,cumulus25-64,debian8-32a,osx1012-64,redhat6-S390X,sles11-S390X,solaris10-SPARC,solaris11-64,ubuntu1604-POWER,windows2012r2-64

**Comment by MikaelSmith** [comment]
I seem to be unable to run this with Jenkins, tests fail with
```
java.lang.IllegalArgumentException: The 'ABS_RESOURCE_REQUESTS_beaker_cpp_pcp_client' build parameter is missing
```

**Comment by McdonaldSeanp** [comment]
jenkins please test pxp-agent on aix71-POWER,amazon6-64,arista4-32,ciscoxr-64,cisconx-64,cumulus25-64,debian8-32a,osx1012-64,redhat6-S390X,sles11-S390X,solaris10-SPARC,solaris11-64,ubuntu1604-POWER,windows2012r2-64

**Comment by McdonaldSeanp** [comment]
@MikaelSmith Just FYI, the reason the tests were failing is because you can't test "cpp-pcp-client" itself since this project has no beaker acceptance setup. So in order to run tests here you can't use the keyword "this" when specifying what project to test. 

The above invocation should work better.

**Comment by MikaelSmith** [comment]
I believe these changes are safe, despite the CI failures.

**Comment by MikaelSmith** [comment]
jenkins please test pxp-agent redhat7-64,ubuntu1604-64,windows2012r2-64

**Comment by MikaelSmith** [comment]
jenkins please test pxp-agent with agent 5.5.x redhat7-64,ubuntu1604-64,windows2012r2-64

**Comment by MikaelSmith** [comment]
jenkins please test pxp-agent with agent 5.5.x on redhat7-64,ubuntu1604-64,windows2012r2-64

**Pull request merged**
